#!/usr/bin/env python3
"""
Seed the ProcessorWatch database with your 400 TakeCard leads.
Run once: python seed_merchants.py
"""
import sqlite3
from monitor import init_db, CONFIG

MERCHANTS = [
    # Format: (name, website, category, pitch, vol_tier)
    ("Maximus Tribe","maximus.com","Telehealth/Hormone","Top TRT platform; pitch recurring billing stability","Large"),
    ("Hone Health","honehealth.com","Telehealth/Hormone","Major TRT telehealth; stable billing = growth unlock","Large"),
    ("Evolve TeleRx","evolvetelemed.com","Telehealth/Hormone","Hormone telehealth 40%+ YoY; processing = bottleneck","Medium"),
    ("Invigor Medical","invigormedical.com","Telehealth/Hormone","Peptide telehealth = hottest processor-adverse vertical","Medium"),
    ("TRT Nation","trtnation.com","Telehealth/Hormone","Growing fast; payment stability = growth constraint","Medium"),
    ("Fountain Life","fountain.life","Telehealth/Hormone","Bryan Johnson adjacent; premium clients; pitch stability","Medium"),
    ("Defy Medical","defymedical.com","Telehealth/Hormone","Tampa telehealth; constantly getting dropped","Medium"),
    ("Gameday Mens Health","gamedaymenshealth.com","Telehealth/Hormone","Franchise telehealth; each location flagged separately","Medium"),
    ("Low T Center","lowtcenter.com","Telehealth/Hormone","National TRT franchise; processor drops = cash flow crisis","Large"),
    ("Fountain TRT","fountaintrt.com","Telehealth/Hormone","Clean brand; testosterone = instant flag anyway","Small-Med"),
    ("BodyLogicMD","bodylogicmd.com","Telehealth/Hormone","BHRT = bioidentical = non-FDA-approved route = flagged","Medium"),
    ("AgelessRx","agelessrx.com","Telehealth/Hormone","Gray-area longevity drugs DTC = processing gap","Medium"),
    ("Titan Medical Center","titanmedicalcenter.com","Telehealth/Hormone","Peptide Rx + subscription = worst combo for processors","Medium"),
    ("American TRT","americantrt.com","Telehealth/Hormone","TRT-only = very few processors even look at this","Small-Med"),
    ("LifeExtension","lifeextension.com","Telehealth/Hormone","Massive volume; processing pain compounds at scale","X-Large"),
    ("Cenegenics","cenegenics.com","Telehealth/Hormone","Very high AOV; chargeback from premium mismatch","Medium"),
    ("Nexel Medical","nexelmedical.com","Telehealth/Hormone","HGH prescriptions online = very few processors period","Small-Med"),
    ("Alpha MD","alphamd.com","Telehealth/Hormone","Controlled-adjacent subscription; pitch stability","Small-Med"),
    ("PeterMD","petermd.com","Telehealth/Hormone","Exact profile Stripe is currently dropping; HOT","Small-Med"),
    ("Vitality Now","vitalitynow.com","Telehealth/Hormone","Supplement + telehealth hybrid = dual risk profile","Medium"),
    ("Confidant Health","confidant.health","Telehealth/Hormone","Controlled Rx telehealth = flagged by every processor","Small-Med"),
    ("Done Health","donefirst.com","Telehealth/Hormone","Schedule II DTC = nearly impossible to place","Medium"),
    ("Cerebral","cerebral.com","Telehealth/Hormone","Under DEA probe; processing nightmare; HOT prospect","Large"),
    ("Klarity Health","klarityhealth.com","Telehealth/Hormone","ADHD telehealth = Schedule II = auto-flagged everywhere","Medium"),
    ("Ahead Health","getheadway.com","Telehealth/Hormone","Growing; stimulant = controlled sub = processor drops","Small-Med"),
    ("Carefree MD","carefreemd.com","Telehealth/Hormone","Subscription telehealth = recurring billing under flagged cat","Medium"),
    ("SteadyMD","steadymd.com","Telehealth/Hormone","Cash-pay telehealth = outside insurance = more scrutiny","Medium"),
    ("Noom Med","noom.com","Telehealth/Hormone","Semaglutide arm gets flagged; massive volume opportunity","X-Large"),
    ("LifeMD","lifemd.com","Telehealth/Hormone","Public company but GLP-1/testosterone still get flagged","Large"),
    ("FunctionHealth","functionhealth.com","Telehealth/Hormone","Membership + labs = recurring billing under health platform","Medium"),
    ("Henry Meds","henrymeds.com","Telehealth/Hormone","Aggressive GLP-1 DTC; processor churn is constant","Large"),
    ("Mochi Health","joinmochi.com","Telehealth/Hormone","Compounded GLP-1 + subscription = dual flag","Medium"),
    ("Ro GLP-1 arm","ro.com","Telehealth/Hormone","Major platform; GLP-1 division = consistent pain","X-Large"),
    ("Hims GLP-1 arm","hims.com","Telehealth/Hormone","Even with brand equity; GLP-1/T lines get flagged","X-Large"),
    ("Calibrate","joincalibrate.com","Telehealth/Hormone","High dropout = systematic chargebacks; ongoing issues","Medium"),
    ("Empower Pharmacy","empowerpharmacy.com","Compounding/GLP-1","Biggest compounder; semaglutide boom = processing crisis","X-Large"),
    ("Hallandale Health","hallandalehealth.com","Compounding/GLP-1","Compounding + peptides = processor nightmare combo","Medium"),
    ("Belmar Pharmacy","belmarpharmacy.com","Compounding/GLP-1","Semaglutide wave = new volume + processing headaches","Medium"),
    ("Tailor Made Compounding","tailormadecompounding.com","Compounding/GLP-1","Growing faster than they can find processors","Medium"),
    ("Olympia Pharmacy","olympiapharmacy.com","Compounding/GLP-1","Known for GH/peptide; processor options extremely limited","Medium"),
    ("Ivy Rx","ivyrx.com","Compounding/GLP-1","FDA gray = processor gray; growing fast","Medium"),
    ("GoalsRx","goalsrx.com","Compounding/GLP-1","Processing can't keep pace with growth; urgent","Small-Med"),
    ("NP2Go","np2go.com","Compounding/GLP-1","Dual risk; growing fast; needs processor","Small-Med"),
    ("Sequence WW","withsequence.com","Compounding/GLP-1","Even WW can't escape semaglutide processor drops","Large"),
    ("Found","joinfound.com","Compounding/GLP-1","GLP-1 subscriptions = high-risk recurring billing","Medium"),
    ("Eden Health GLP-1","edenmen.com","Compounding/GLP-1","Every product arm adds new processor risk layer","Small-Med"),
    ("Mixlab Pharmacy","mixlab.com","Compounding/GLP-1","Vet + human = no processor category fits","Small-Med"),
    ("Strive Pharmacy","strivepharmacy.com","Compounding/GLP-1","Direct-dispense model; no standard merchant account","Small-Med"),
    ("Pivotal Compounding","pivotalcompounding.com","Compounding/GLP-1","Launched at peak sema demand; no long-term processor","Small-Med"),
    ("Mountain West Pharmacy","mountainwestpharmacy.com","Compounding/GLP-1","Regional going national = processing transition","Small-Med"),
    ("Sublime Health Compounding","sublimecompounding.com","Compounding/GLP-1","Smaller compounder scaling = most desperate for processing","Small-Med"),
    ("Peninsula Pharmacy","peninsulacompounding.com","Compounding/GLP-1","DTC pivot = exact moment to lock in a processor","Small-Med"),
    ("Red Rock Pharmacy","redrockpharmacy.com","Compounding/GLP-1","Utah market growing; alt-med + compounding friendly","Small-Med"),
    ("Pure Life Rx","pureliferx.com","Compounding/GLP-1","Alt-med positioning = even harder to place","Small-Med"),
    ("Simple Meds","simplemeds.com","Compounding/GLP-1","Thin margins = processor rates are survival","Medium"),
    ("Ahead Pharmacy","aheadpharmacy.com","Compounding/GLP-1","Tech-forward compounder; needs processor that gets the space","Small-Med"),
    ("Pharmacy Rx World","pharmacyrxworld.com","Compounding/GLP-1","Offshore Rx = cross-border + controlled = impossible","Small-Med"),
    ("CivicaMD","civicamd.com","Compounding/GLP-1","Non-profit DTC pharma = unconventional; processors auto-decline","Medium"),
    ("Woodland Hills Compounding","woodlandhillscompounding.com","Compounding/GLP-1","LA market; high-income clients; premium CB exposure","Small-Med"),
    ("PCAB Compounding Directory","pcab.org","Compounding/GLP-1","Directory = 500+ warm leads; every one needs processing","X-Large (market)"),
    ("The Wellness Company","twc.health","Alt Medicine/Ivermectin","Publicly vocal about processor battles; warm cold call","Large"),
    ("SpeakWithAnMD","speakwithanmd.com","Alt Medicine/Ivermectin","One of first ivermectin sites; constant instability","Medium"),
    ("Americas Frontline Doctors","americasfrontlinedoctors.org","Alt Medicine/Ivermectin","Well-documented payment processor battles","Medium"),
    ("GreenHill Pharmacy","greenhill-pharmacy.com","Alt Medicine/Ivermectin","Processors decline on Google search of name alone","Small-Med"),
    ("Push Health","pushhealth.com","Alt Medicine/Ivermectin","Off-label prescribing = processor declines on description","Medium"),
    ("Mercola Market","mercola.com","Alt Medicine/Ivermectin","Banned from processors before; very motivated prospect","X-Large"),
    ("Health Ranger Store","healthrangerstore.com","Alt Medicine/Ivermectin","High volume; mainstream processors have dropped them","Large"),
    ("Tele-MedMD","telemedmd.com","Alt Medicine/Ivermectin","Cash-pay functional medicine; underserved everywhere","Small-Med"),
    ("Sanoviv Medical","sanoviv.com","Alt Medicine/Ivermectin","High-ticket alt medicine; cross-border + alt-med = hard","Medium"),
    ("Childrens Health Defense","childrenshealthdefense.org","Alt Medicine/Ivermectin","High-profile; political positioning = processor instability","Medium"),
    ("Epoch Times Health","epochtimes.com","Alt Medicine/Ivermectin","Very high traffic; political adjacency = reluctance","Large"),
    ("FLCCC Pharmacies","flccc.net","Alt Medicine/Ivermectin","FLCCC pharmacy list = warm leads; all need processing","Large (market)"),
    ("Natural Health Sherpa","naturalhealthsherpa.com","Alt Medicine/Ivermectin","Anti-pharma positioning alone flags many processors","Small-Med"),
    ("WND Shop","shop.wnd.com","Alt Medicine/Ivermectin","Conservative media affiliate supplement sales","Small-Med"),
    ("Laissez Faire Club","laissezbookclub.com","Alt Medicine/Ivermectin","DR + subscription + alt-health = perfect trifecta","Medium"),
    ("Bypass MD","bypassmd.com","Alt Medicine/Ivermectin","Physician contrarian brand; supplement + alt positioning","Small-Med"),
    ("Int Al Physicians","ipaurgentcare.org","Alt Medicine/Ivermectin","Physician network; payment needs across affiliates","Small-Med"),
    ("Pure Life Farmacy","purelifefarmacy.com","Alt Medicine/Ivermectin","Natural remedy brand; bold claims = processor concern","Small-Med"),
    ("Organic Alliances","organicalliances.com","Alt Medicine/Ivermectin","Multi-brand alt-health; one convo for multiple brands","Small-Med"),
    ("Brownstone Institute","brownstone.org","Alt Medicine/Ivermectin","Politically exposed; supplement sales; processors declined","Small"),
    ("Joovv","joovv.com","Biohacking/Longevity","Market leader RLT; high AOV = large chargeback $ exposure","Large"),
    ("PlatinumLED","platinumledtherapylights.com","Biohacking/Longevity","High-ticket devices; health claims flag processors","Medium"),
    ("Mito Red Light","mitored.com","Biohacking/Longevity","Price-competitive vs Joovv; same processing headaches","Medium"),
    ("HigherDOSE","higherdose.com","Biohacking/Longevity","Celebrity brand; aggressive health claims; high CB $","Large"),
    ("Flexpulse PEMF","flexpulse.com","Biohacking/Longevity","PEMF = medical device adjacent without FDA clearance","Small-Med"),
    ("Spooky2 Rife","spooky2.com","Biohacking/Longevity","Rife machines = nearly impossible to process anywhere","Small-Med"),
    ("EarthPulse PEMF","earthpulse.net","Biohacking/Longevity","Very aggressive health claims = processor + FDA concern","Small-Med"),
    ("Echo H2 Water","echoh2o.com","Biohacking/Longevity","Gray area health claims; processors don't know category","Small-Med"),
    ("Troscriptions","troscriptions.com","Biohacking/Longevity","Novel product; processors have no category for MB","Small-Med"),
    ("MitoZen","mitozen.com","Biohacking/Longevity","MB = drug in some FDA interpretations = auto-declined","Small-Med"),
    ("Apollo Neuro","apolloneuro.com","Biohacking/Longevity","$350 device with health claims; gray FDA clearance","Medium"),
    ("BrainTap","braintap.com","Biohacking/Longevity","Brain entrainment; mental health claims; no clearance","Small-Med"),
    ("Hapbee","hapbee.com","Biohacking/Longevity","So novel processors auto-decline; no category exists","Small-Med"),
    ("Levels Health","levelshealth.com","Biohacking/Longevity","Rx device DTC subscription = processing gap to fill","Large"),
    ("Signos","signos.com","Biohacking/Longevity","Same as Levels; Rx device DTC subscription = flagged","Medium"),
    ("InsideTracker","insidetracker.com","Biohacking/Longevity","Health data + supplement = two gray areas; subscription","Medium"),
    ("Upgraded Formulas","upgradedformulas.com","Biohacking/Longevity","Novel protocol; processors auto-decline novel health","Small-Med"),
    ("Bryan Johnson Blueprint","blueprint.bryanjohnson.co","Biohacking/Longevity","High-profile; aggressive anti-aging claims = flagged","Large"),
    ("Neurohacker Collective","neurohacker.com","Biohacking/Longevity","Subscription + clinical brain health claims = dual risk","Medium"),
    ("Vital Reaction H2","vitalreaction.com","Biohacking/Longevity","Novel category; very few processors take inhalers","Small-Med"),
    ("Kona Kratom","konakratom.com","Kratom/Botanicals","Compliance-first pitch; AKA cert = conversation opener","Small-Med"),
    ("MIT45","mit45.com","Kratom/Botanicals","Premium extract; $15-30/unit; massive volume; trophy acct","Large"),
    ("OPMS Kratom","opmskratom.com","Kratom/Botanicals","Market leader shots; very high AOV; trophy account","Large"),
    ("Botanic Tonics Feel Free","botanictonics.com","Kratom/Botanicals","Regulatory urgency = urgency to lock in stable processing NOW","Large"),
    ("Krave Kratom","kravebrands.com","Kratom/Botanicals","High volume across channels; dual processing pain","Medium"),
    ("Krabot","krabot.com","Kratom/Botanicals","Lab-tested = compliance pitch is natural opener","Small-Med"),
    ("Earth Kratom","earthkratom.com","Kratom/Botanicals","High velocity; payment pain across both channels","Medium"),
    ("Club13 Botanicals","club13botanicals.com","Kratom/Botanicals","Multi-product high-risk; growth = growing processing need","Medium"),
    ("Kingdom Kratom","kingdomkratom.com","Kratom/Botanicals","Solid mid-size; probably on suboptimal processor","Small-Med"),
    ("Gaia Ethnobotanical","gaiaethnobotanical.com","Kratom/Botanicals","Multi-botanical = stacked risk; boutique with growing vol","Small-Med"),
    ("Kratom Country","kratomcountry.com","Kratom/Botanicals","High volume; established; likely on bad processor","Medium"),
    ("Herbal Salvation","herbalsalvation.com","Kratom/Botanicals","Multi-herbal; herbal combos add additional risk flags","Small-Med"),
    ("Underground Botanicals","undergroundbotanicals.com","Kratom/Botanicals","Edgy branding increases processor reluctance","Small-Med"),
    ("Velvet Lotus Kratom","velvetlotuskratom.com","Kratom/Botanicals","High AOV = bigger chargeback $ when disputes happen","Small"),
    ("Fresh Botanical Kratom","freshbotanical.com","Kratom/Botanicals","Subscription kratom = recurring billing under flagged cat","Small-Med"),
    ("Bikhuk","bikhuk.com","Kratom/Botanicals","International kratom = FX + category = two hard problems","Small-Med"),
    ("Phytoextractum","phytoextractum.com","Kratom/Botanicals","Extracts = higher $ per order = larger CB exposure","Medium"),
    ("Super Speciosa","superspeciosa.com","Kratom/Botanicals","AKA cert = lead with compliance angle","Medium"),
    ("Left Coast Kratom","leftcoastkratom.com","Kratom/Botanicals","Regional with growing DTC; hasn't shopped rates","Small-Med"),
    ("Remarkable Herbs","remarkableherbs.com","Kratom/Botanicals","Multi-channel = multiple processor headaches; consolidation","Medium"),
    ("Hometown Hero Hemp","hometownherohemp.com","Hemp/Alt-Cannabinoids","They talk about processor headaches publicly; call them today","Large"),
    ("Delta Extrax","deltaextrax.com","Hemp/Alt-Cannabinoids","Major brand; definitely on multiple processors to hedge","Large"),
    ("Flying Monkey Delta","flyingmonkeydelta.com","Hemp/Alt-Cannabinoids","High-volume; needs B2B and DTC channel processing","Large"),
    ("Cake Hemp Co","cakehempco.com","Hemp/Alt-Cannabinoids","One of biggest delta disposable brands; massive throughput","Large"),
    ("Urb Finest Flowers","urb.com","Hemp/Alt-Cannabinoids","Each new compound = new processing risk layer","Medium"),
    ("Moonwlkr","moonwlkr.com","Hemp/Alt-Cannabinoids","Growing subscription base; recurring billing under delta cat","Medium"),
    ("ATLRx","atlrx.com","Hemp/Alt-Cannabinoids","THCA in flux; processors dropping brands NOW = call urgently","Large"),
    ("TRE House","trehouse.com","Hemp/Alt-Cannabinoids","Novel compound stacking = no processor category; own it","Medium"),
    ("Galaxy Treats","galaxytreats.com","Hemp/Alt-Cannabinoids","Delta + amanita niche = no processor category = own it","Medium"),
    ("Area 52","area52.com","Hemp/Alt-Cannabinoids","Growing DTC; pitch on stability as they scale","Medium"),
    ("CannaAid","cannaaidshop.com","Hemp/Alt-Cannabinoids","Every new compound adds processing friction","Medium"),
    ("Mellow Fellow","mellowfellow.com","Hemp/Alt-Cannabinoids","Multi-compound blends; each = potential processing flag","Medium"),
    ("iDELTA8","idelta8.com","Hemp/Alt-Cannabinoids","Volume = pain when processors drop without warning","Medium"),
    ("Harbor City Hemp","harborcityhemp.com","Hemp/Alt-Cannabinoids","Dual channel; needs processing for both B2B and DTC","Medium"),
    ("Botany Farms","botanyfarms.com","Hemp/Alt-Cannabinoids","THCA in flux; processors dropping NOW = call urgently","Medium"),
    ("Mr Hemp Flower","mrhempflower.com","Hemp/Alt-Cannabinoids","Raw flower = niche within niche; very few processors","Medium"),
    ("Cannaflower","cannaflower.com","Hemp/Alt-Cannabinoids","High-ticket + flower subcategory = processing headaches","Medium"),
    ("3Chi","3chi.com","Hemp/Alt-Cannabinoids","OG brand; been dropped + replaced most; pitch stability","Large"),
    ("Dozo Delta","dozo.com","Hemp/Alt-Cannabinoids","High velocity = high volume = processing matters at scale","Medium"),
    ("Genesis Blends","genesisblends.com","Hemp/Alt-Cannabinoids","Processors have no category; you'd be their first stable","Small-Med"),
    ("Canna River","cannariver.com","Hemp/Alt-Cannabinoids","Thin margins = processor rates matter most; pitch savings","Medium"),
    ("Hi On Nature","hionnature.com","Hemp/Alt-Cannabinoids","Two gray areas combined = processing nightmare","Small-Med"),
    ("Puro Cannagars","puro.com","Hemp/Alt-Cannabinoids","Hemp cigar = tobacco + cannabis combo; no category","Small-Med"),
    ("Secret Nature CBD","secretnaturecbd.com","Hemp/Alt-Cannabinoids","Premium flower + raw hemp = dual processing issues","Medium"),
    ("Plain Jane CBD","plainjane.com","Hemp/Alt-Cannabinoids","Raw flower specialist; limited options in sub-category","Medium"),
    ("MN Nice Ethnobotanicals","mnniceethnobotanicals.com","Amanita/Psychedelics","Most established legal psychedelic vendor; almost no options","Medium"),
    ("Mushroom Lyfe","mushroomlyfe.com","Amanita/Psychedelics","Growing fast in amanita; zero mainstream processor options","Small-Med"),
    ("Schedule35","schedule35.com","Amanita/Psychedelics","Aggregates hardest-to-process categories under one roof","Small-Med"),
    ("Kanna Depot","kannadepot.com","Amanita/Psychedelics","Kanna = legal mood enhancer; processors have no category","Small-Med"),
    ("Blue Lotus Shop","bluelotusshop.com","Amanita/Psychedelics","Legal everywhere; processors auto-decline without understanding","Small"),
    ("Synthesis Retreat","synthesisretreat.com","Amanita/Psychedelics","Cross-border + psychedelic adjacency = mainstream impossible","Small-Med"),
    ("Psychedelic Passage","psychedelicpassage.com","Amanita/Psychedelics","Legal in OR/CO; processors don't care about state law","Small-Med"),
    ("DoubleBlind Shop","doubleblindmag.com","Amanita/Psychedelics","High-profile brand; processors won't touch psychedelic-adj","Small-Med"),
    ("WholeCelium","wholecelium.com","Amanita/Psychedelics","Pioneer in legal mushroom DTC; first-mover opportunity","Small-Med"),
    ("Real Mushrooms","realmushrooms.com","Amanita/Psychedelics","Very large brand; cognitive claims flag processors at scale","Large"),
    ("Host Defense Paul Stamets","hostdefense.com","Amanita/Psychedelics","Stamets name = psychedelic adjacency in processor systems","Medium"),
    ("Zaza Red Tianeptine","zazared.com","Amanita/Psychedelics","Tianeptine = opioid-like; processors decline universally","Small-Med"),
    ("Kava.com","kava.com","Amanita/Psychedelics","Kava DTC growing fast as bar culture spreads; processor pain","Medium"),
    ("Root of Happiness","rootofhappiness.com","Amanita/Psychedelics","Long-standing kava brand; stability always a challenge","Small-Med"),
    ("Nakamal at Home","nakamalathome.com","Amanita/Psychedelics","OG kava; knows exactly why they need a specialist","Small-Med"),
    ("Kavafied","kavafied.com","Amanita/Psychedelics","Hardware + consumable = two processing conversations","Small-Med"),
    ("Sacred Succulents","sacredsucculents.com","Amanita/Psychedelics","Legal product; processors decline regardless of legality","Small"),
    ("MHRB.net","mhrb.net","Amanita/Psychedelics","Legal to sell; processors treat as DMT anyway","Small"),
    ("Levitate","levitatelife.com","Amanita/Psychedelics","Dual gray-area = two independent reasons to decline","Small-Med"),
    ("North Spore","northspore.com","Amanita/Psychedelics","Grow kits + functional = intent flags processor systems","Small-Med"),
    ("Elf Bar USA","elfbar.com","Vape/Nicotine","Most recognized disposable; massive US volume","X-Large"),
    ("Lost Mary","lostmary.com","Vape/Nicotine","EB Design brand family; high volume in convenience+online","Large"),
    ("Geek Bar","geekbar.com","Vape/Nicotine","Fast-growing; same processor issues as all disposables","Large"),
    ("Funky Republic","funkyrepublic.com","Vape/Nicotine","EB Design subsidiary; tied to largest disposable family","Large"),
    ("Puff Bar","puffbar.com","Vape/Nicotine","Most searched disposable; enforcement + blacklist = pain","Large"),
    ("Element Vape","elementvape.com","Vape/Nicotine","Biggest online vape retailer; costs at scale are huge","Large"),
    ("EightVape","eightvape.com","Vape/Nicotine","Thin margins = 20bps difference = profit or loss","Large"),
    ("Naked 100 E-Liquid","naked100.com","Vape/Nicotine","Top shelf e-liquid; high-volume DTC; regulatory burden","Medium"),
    ("Jam Monster","jammonster.com","Vape/Nicotine","One of most popular e-juice brands; high volume = pain","Medium"),
    ("VGOD","vgod.com","Vape/Nicotine","Premium brand; influencer marketing; high AOV","Medium"),
    ("ZYN Nicotine Pouches","zyn.com","Vape/Nicotine","Huge volume; online sales harder than retail","Large"),
    ("On Nicotine Pouches","onnicotine.com","Vape/Nicotine","Even Altria backing doesn't help online nicotine","Large"),
    ("Rogue Nicotine","rogue.com","Vape/Nicotine","Indie = tighter margins + processor pain = motivated","Small-Med"),
    ("Lucy Goods","lucy.co","Vape/Nicotine","Startup; VC-backed; still gets flagged for nicotine cat","Medium"),
    ("Grinds Coffee Pouches","grindsco.com","Vape/Nicotine","Coffee pouches declined as tobacco adjacent; it's coffee","Small-Med"),
    ("Air Factory E-Juice","airfactoryeliquid.com","Vape/Nicotine","Popular in vape shops + online; dual channel processing","Medium"),
    ("Halo Cigs","halocigs.com","Vape/Nicotine","OG e-cig; rate shopping opportunity","Medium"),
    ("VaporDNA","vapordna.com","Vape/Nicotine","Split pitch: hardware vs. liquid MCCs separated","Medium"),
    ("Direct Vapor","directvapor.com","Vape/Nicotine","Well-established; worth going in on rates","Large"),
    ("FRE Tobacco-Free Nicotine","fretobacco.com","Vape/Nicotine","Novel = no processor category = auto-declined","Small-Med"),
    ("Silencer Shop","silencershop.com","Firearms/Tactical","Market leader; NFA + high AOV = processing complexity","Large"),
    ("Solvent Traps Direct","solventtrapsdirect.com","Firearms/Tactical","Huge market; legal dual-use; processors declining entire cat","Medium"),
    ("Dead Air Armament","deadairarmament.com","Firearms/Tactical","Growing suppressor brand; NFA = processing challenge","Medium"),
    ("Aero Precision","aeroprecisionusa.com","Firearms/Tactical","Largest AR component maker; DTC sales = headaches","Large"),
    ("Magpul","magpul.com","Firearms/Tactical","Huge brand; state mag restrictions = compliance headache","X-Large"),
    ("Palmetto State Armory","palmettostatearmory.com","Firearms/Tactical","Trophy account; massive volume; winning this = landmark","X-Large"),
    ("Primary Arms","primaryarms.com","Firearms/Tactical","Optics flagged with firearms; large DTC operation","Large"),
    ("Ammo.com","ammo.com","Firearms/Tactical","Massive volume; specialty processor but rates = huge var","X-Large"),
    ("Lucky Gunner","luckygunner.com","Firearms/Tactical","Very high volume; in-stock = massive throughput","Large"),
    ("GunMag Warehouse","gunmagwarehouse.com","Firearms/Tactical","State compliance layer makes processing more complex","Medium"),
    ("Alien Gear Holsters","aliengearholsters.com","Firearms/Tactical","CCW = firearms adjacent = processing questions universally","Medium"),
    ("Vortex Optics","vortexoptics.com","Firearms/Tactical","Optics alone = flagged; massive volume = big opportunity","X-Large"),
    ("Blade HQ","bladehq.com","Firearms/Tactical","One of biggest knife retailers; state restrictions = burden","Large"),
    ("Microtech Knives","microtechknives.com","Firearms/Tactical","Auto knives = banned in many states; compliance concerns","Medium"),
    ("SMKW","smkw.com","Firearms/Tactical","Largest knife retailer nationally; big processing opportunity","Large"),
    ("Benchmade","benchmade.com","Firearms/Tactical","Premium knife; high AOV; state restrictions = complex","Large"),
    ("Stealth Arms","stealtharms.com","Firearms/Tactical","80% lowers = very few processors post-ATF ruling","Small-Med"),
    ("Geissele Automatics","geissele.com","Firearms/Tactical","Premium trigger maker; high-AOV DTC; firearms flag","Medium"),
    ("LaRue Tactical","laruetactical.com","Firearms/Tactical","Texas brand; premium = high AOV; firearms accessory = flagged","Medium"),
    ("JP Enterprises","jprifles.com","Firearms/Tactical","Competition-grade; limited processor options for FFL sellers","Small-Med"),
    ("Steel Supplements","steelsupplements.com","Aggressive Supplements","Growing fast; boundary-pushing ingredients = processor flags","Medium"),
    ("Bucked Up","buckedup.com","Aggressive Supplements","Fastest-growing supplement brand; high DTC + retail volume","Large"),
    ("Anabolic Warfare","anabolicwarfare.com","Aggressive Supplements","Brand name alone triggers automated processor screening","Small-Med"),
    ("Redcon1","redcon1.com","Aggressive Supplements","One of the larger brands; military + high stim = scrutiny","Large"),
    ("Apollon Nutrition","apollonnutrition.com","Aggressive Supplements","Place extreme stim = own the referral network","Medium"),
    ("Hi-Tech Pharmaceuticals","hi-techpharmaceuticals.com","Aggressive Supplements","High volume + high risk; big upside with right risk deal","Large"),
    ("Chaos and Pain","chaosandpain.com","Aggressive Supplements","Ingredient controversy = rough processor history","Medium"),
    ("Blackstone Labs","blackstonelabs.com","Aggressive Supplements","Went through serious disruption; they remember the pain","Medium"),
    ("Alpha Lion","alphalion.com","Aggressive Supplements","Growing brands need stable processing as volume rises","Medium"),
    ("Gorilla Mind","gorillamind.com","Aggressive Supplements","Cernovich brand; huge audience; high-volume DTC","Large"),
    ("Huge Supplements","hugesupplements.com","Aggressive Supplements","Growing fast; brand name = flag; needs stable processor","Medium"),
    ("Enhanced Labs","enhancedlabs.com","Aggressive Supplements","Mike O'Hearn brand; Enhanced triggers screening","Small-Med"),
    ("Condemned Labz","condemnedlabz.com","Aggressive Supplements","Getting to them early = long-term relationship","Small-Med"),
    ("Black Market Labs","blackmarketlabs.com","Aggressive Supplements","Literally triggers automatic declines on brand name alone","Small-Med"),
    ("Primeval Labs","primevallabs.com","Aggressive Supplements","Racetam = pharmacy-adjacent = flagged category","Small-Med"),
    ("Dark Labs","darkm.co","Aggressive Supplements","Cross-border + extreme stim = nearly impossible; big win","Small-Med"),
    ("Inspired Nutraceuticals","inspirednutraceuticals.com","Aggressive Supplements","Known for pushing limits; solid brand in gray zone","Medium"),
    ("Hard Rhino","hardrhino.com","Aggressive Supplements","Name triggers declines; B2B supplier = TakeCard angle","Medium"),
    ("Competitive Edge Labs","competitivedgelabs.com","Aggressive Supplements","Past prohormone history = permanent flag; pitch clean record","Small-Med"),
    ("DNM Nutra","dnmnutra.com","Aggressive Supplements","B2B wholesale in flagged cats; one acct = multiple brands","Medium"),
    ("Innovative Labs Hellboy","innovativelabsfl.com","Aggressive Supplements","Extreme branding around boundary ingredients","Small-Med"),
    ("Panda Supps","pandasupps.com","Aggressive Supplements","Social media brand; needs processor that grows with them","Small-Med"),
    ("NutraBio Labs","nutrabio.com","Aggressive Supplements","Clean label brand; category still flagged; compliance pitch","Medium"),
    ("Metabolic Nutrition","metabolicnutrition.com","Aggressive Supplements","Long-standing; borderline history = flagged even today","Medium"),
    ("Bucked Up B2B Wholesale","dasprotein.com","Aggressive Supplements","B2B wholesale angle; TakeCard B2B + high-risk = fit","Large"),
    ("Pure Rawz","purerawz.com","Peptides/Research Chem","Research chemical = extreme processor friction; few options","Medium"),
    ("Umbrella Labs","umbrellalab.com","Peptides/Research Chem","Established vendor; options limited = leverage their pain","Medium"),
    ("Sports Technology Labs","sportstechnologylabs.com","Peptides/Research Chem","Fast-growing; processor drops inevitable in this category","Medium"),
    ("Paradigm Peptides","paradigmpeptides.com","Peptides/Research Chem","Consistent headaches = motivated prospect","Small-Med"),
    ("Amino Asylum","aminoasylum.com","Peptides/Research Chem","Community-known; processor pain constant; needs specialist","Small-Med"),
    ("Enhanced Athlete","enhancedathlete.com","Peptides/Research Chem","Legal battles + processing issues = very motivated","Medium"),
    ("SwissChems","swisschems.is","Peptides/Research Chem","Offshore + SARMs = nearly impossible; solving = big win","Medium"),
    ("Core Peptides","corepeptides.com","Peptides/Research Chem","Lab-tested = compliance pitch; TakeCard angle is natural","Small-Med"),
    ("Behemoth Labz","behemothlabz.com","Peptides/Research Chem","Multi-category; looking for someone who gets all of it","Small-Med"),
    ("IRC.bio","irc.bio","Peptides/Research Chem","Compounds so obscure processors just auto-decline","Small-Med"),
    ("Southern SARMs","southernsarms.com","Peptides/Research Chem","Growing national; needs processor that gets research chems","Small-Med"),
    ("Mind Lab Pro","mindlabpro.com","Peptides/Research Chem","Very large global brand; clinical-adjacent = friction at scale","Large"),
    ("Thesis Nootropics","takethesis.com","Peptides/Research Chem","Subscription + health claims = dual risk; growing fast","Medium"),
    ("Nooceptin","nooceptin.com","Peptides/Research Chem","Clinical claims + UK origin = cross-border + health claim","Small-Med"),
    ("Double Wood Supplements","doublewoodsupplements.com","Peptides/Research Chem","Some nootropics flag automated processor screening","Medium"),
    ("Pure Nootropics","purenootropics.net","Peptides/Research Chem","Older brand; loyal community; processor instability ongoing","Small-Med"),
    ("CosmicNootropic","cosmicnootropic.com","Peptides/Research Chem","International + research chem = cross-border dual flag","Small-Med"),
    ("Ceretropic","ceretropic.com","Peptides/Research Chem","EU-origin research chemicals; intl + research chem = two flags","Small-Med"),
    ("Biotech Peptides","biotechpeptides.com","Peptides/Research Chem","Growing; almost no mainstream options; pitch that angle","Medium"),
    ("Peptide Sciences","peptidesciences.com","Peptides/Research Chem","Established; high AOV peptide orders; consistent pain","Medium"),
    ("Nugenix","nugenix.com","Sexual Enhancement","Huge DTC; massive DR = high chargeback from mass market","Large"),
    ("ExtenZe","extenze.com","Sexual Enhancement","Iconic brand; FTC history = permanent processor flag","Large"),
    ("VigRX Plus","vigrxplus.com","Sexual Enhancement","Long-running; affiliate marketing = elevated CB ratios","Large"),
    ("Male Extra","maleextra.com","Sexual Enhancement","International; US DTC channel; category flag is universal","Medium"),
    ("Performer 8","performer8.com","Sexual Enhancement","Subscription + bold claims = high risk stack","Medium"),
    ("ProSolution Plus","prosolution.com","Sexual Enhancement","PE claims = quasi-medical = FDA + processor concern","Medium"),
    ("Semenax","semenax.com","Sexual Enhancement","Explicit claims; very few processors touch this subcat","Medium"),
    ("Max Performer","maxperformer.com","Sexual Enhancement","Category clone; same processing headaches; motivated prospect","Medium"),
    ("Viasil","viasil.com","Sexual Enhancement","Cross-border + ED supplement = processing friction","Medium"),
    ("Male UltraCore","maleultracore.com","Sexual Enhancement","T + ED combo = dual-category risk flag","Small-Med"),
    ("Testogen","testogen.com","Sexual Enhancement","Large DTC; UK origin; aggressive affiliate marketing","Medium"),
    ("Testo Prime","testoprime.com","Sexual Enhancement","Recurring billing + hormone adjacent = doubly flagged","Medium"),
    ("Prime Male","primemale.com","Sexual Enhancement","DR to older demo = elevated chargeback propensity","Medium"),
    ("TestRX","testrx.com","Sexual Enhancement","DR + older demo = higher chargeback rate historically","Small-Med"),
    ("Hunter Test","hunter-evolve.com","Sexual Enhancement","High AOV in sensitive category = large CB $ per dispute","Small-Med"),
    ("T-Drive Inno Supps","innosupps.com","Sexual Enhancement","Growing brand; T-support = flagged component","Medium"),
    ("Volume Pills","volumepills.com","Sexual Enhancement","Explicit; very few payment options for this subcat","Medium"),
    ("Alpha Male MD","alphamalemd.com","Sexual Enhancement","Telehealth + sexual enhancement supplement = dual high-risk","Small-Med"),
    ("Keeps","keeps.com","Sexual Enhancement","T supplement arm gets flagged separate from hair arm","Large"),
    ("Roman supplement arm","ro.com","Sexual Enhancement","Even well-known brands get flagged for T + ED OTC lines","X-Large"),
    ("My Patriot Supply","mypatriotsupply.com","Prepper/Survivalist","Massive DR advertiser; elevated CBs from mass market DR","X-Large"),
    ("4Patriots","4patriots.com","Prepper/Survivalist","High DR; patriot brand = political + DR risk = dual flag","Large"),
    ("ReadyWise","readywise.com","Prepper/Survivalist","Subscription emergency food = continuity under survivalist","Medium"),
    ("Legacy Food Storage","legacyfoodstorage.com","Prepper/Survivalist","High AOV kits; single large purchases = CB exposure","Medium"),
    ("Augason Farms","augasonfarms.com","Prepper/Survivalist","Walmart + DTC = split processing need; worth conversation","Large"),
    ("Valley Food Storage","valleyfs.com","Prepper/Survivalist","Premium emergency food; growing; needs scalable processing","Small-Med"),
    ("Nutrient Survival","nutrientsurvival.com","Prepper/Survivalist","Military angle; processor still sees survivalist food cat","Small-Med"),
    ("SurvivalFrog","survivalfrog.com","Prepper/Survivalist","Broad catalog; EDC + prepper market growing fast","Small-Med"),
    ("Survival Life","survivallife.com","Prepper/Survivalist","Very high DR; continuity club = highest CB in DR","Large"),
    ("Harvest Right","harvestright.com","Prepper/Survivalist","Very high AOV freeze-dryers = large CB $ exposure","Medium"),
    ("Freeze Dry Guy","freezedryguy.com","Prepper/Survivalist","Home freeze-dryer market booming; growing niche supplier","Small-Med"),
    ("Titan Survival","titansurvivalgear.com","Prepper/Survivalist","Military theme + survival = two processor flags","Small"),
    ("PrepSurvivor","prepsurvivor.com","Prepper/Survivalist","Content + commerce; survivalist niche growing","Small"),
    ("APOCABOX","apocabox.com","Prepper/Survivalist","Subscription survival = continuity; boxes disappoint = CBs","Small-Med"),
    ("MRE Star","mrestar.com","Prepper/Survivalist","MREs for civilians; gov positioning doesn't help","Small-Med"),
    ("Thrive Life","thrivelife.com","Prepper/Survivalist","MLM + subscription = dual high-risk; very hard to place","Medium"),
    ("Emergency Essentials","beprepared.com","Prepper/Survivalist","OG prepper brand; probably hasn't aggressively shopped rates","Medium"),
    ("Fieldcraft Survival","fieldcraftsurvival.com","Prepper/Survivalist","Veteran brand; military adjacent = processor flag","Small-Med"),
    ("Patriots Network SHTF","shtfplan.com","Prepper/Survivalist","Political + prepper = dual processor flag","Small-Med"),
    ("Heart and Soil","heartandsoil.co","Carnivore/Ancestral","Very large brand; claims on desiccated organs = flagged","Large"),
    ("Ancestral Supplements","ancestralsupplements.com","Carnivore/Ancestral","Market pioneer; health claims on raw organs = flagged","Large"),
    ("Force of Nature Meats","forceofnaturemeats.com","Carnivore/Ancestral","Subscription raw meat = perishable + continuity = dual flag","Medium"),
    ("US Wellness Meats","grasslandbeef.com","Carnivore/Ancestral","Long-established raw meat DTC; ancestral diet OG brand","Medium"),
    ("White Oak Pastures","whiteoakpastures.com","Carnivore/Ancestral","High AOV farm brand; premium = CB risk from expectations","Medium"),
    ("Seven Sons Farm","sevensons.net","Carnivore/Ancestral","Subscription meat going national = processing transition","Small-Med"),
    ("Wild Pastures","wildpastures.com","Carnivore/Ancestral","Subscription-only = recurring billing = extra scrutiny","Small-Med"),
    ("Snake River Farms","snakeriverfarms.com","Carnivore/Ancestral","$100-500 orders; CB from premium expectation mismatch","Large"),
    ("Primal Pastures","primalpastures.com","Carnivore/Ancestral","Going national = processing transition moment = pitch now","Small-Med"),
    ("Paleovalley","paleovalley.com","Carnivore/Ancestral","Well-known ancestral health DTC; bold ingredient claims","Medium"),
    ("Good Ranchers","goodranchers.com","Carnivore/Ancestral","Christian values + subscription = political adjacency + continuity","Medium"),
    ("Gaucho Ranch","gauchoranch.com","Carnivore/Ancestral","Cross-border sourcing + DTC = extra processing friction","Small-Med"),
    ("Old Salt Merchants","oldsaltmerchants.com","Carnivore/Ancestral","Premium dry-aged; high AOV; perishable + premium = CB risk","Small-Med"),
    ("Nose to Tail","nosetotail.org","Carnivore/Ancestral","International raw organ = food safety + cross-border = hard","Small"),
    ("Raw Paws","rawpaws.com","Carnivore/Ancestral","Human + pet raw food = food safety flag; dual market","Small-Med"),
    ("Honest Paws","honestpaws.com","Pet CBD/Wellness","One of biggest pet CBD brands; very aggressive health claims","Large"),
    ("Pet Releaf","petreleaf.com","Pet CBD/Wellness","NASC cert doesn't matter to processors; still declined","Medium"),
    ("HolistaPet","holistapet.com","Pet CBD/Wellness","Cancer + seizure claims for pets = FDA + processor concern","Medium"),
    ("King Kanine","kingkanine.com","Pet CBD/Wellness","Premium; high AOV; still flagged despite clean brand","Small-Med"),
    ("Canna-Pet","canna-pet.com","Pet CBD/Wellness","OG pet hemp; navigated processor issues for years = hot lead","Small-Med"),
    ("ElleVet Sciences","ellevetsciences.com","Pet CBD/Wellness","Most validated pet CBD; vet support doesn't help processing","Small-Med"),
    ("Petly CBD","petlycbd.com","Pet CBD/Wellness","Subscription + CBD = any cancellation = CB; dual flag","Small-Med"),
    ("Innovet Pet","innovetpet.com","Pet CBD/Wellness","Very specific medical claims for pets = FDA + processor concern","Medium"),
    ("HempMy Pet","hempmypet.com","Pet CBD/Wellness","Organic cert = cleaner; still can't get mainstream processing","Small-Med"),
    ("Paw CBD","pawcbd.com","Pet CBD/Wellness","CW brand; pet CBD arm has processing issues","Medium"),
    ("Medterra Pet","medterrapets.com","Pet CBD/Wellness","Medterra = large CBD; pet extension flagged separately","Medium"),
    ("NuLeaf Naturals pets","nuleafnaturals.com","Pet CBD/Wellness","Premium brand; pet hemp needs separate processing","Medium"),
    ("Zen Pup","zenpup.com","Pet CBD/Wellness","Anxiety claims for dogs = mental health flagging","Small"),
    ("CBDPure pets","cbdpure.com","Pet CBD/Wellness","Human CBD to pets; pet arm = separate headaches","Small-Med"),
    ("cbdMD pets","cbdmd.com","Pet CBD/Wellness","Large CBD brand; pet line still flagged despite main brand","Medium"),
    ("JM Bullion","jmbullion.com","Precious Metals","Largest US bullion retailer; price swings = CB spikes","X-Large"),
    ("APMEX","apmex.com","Precious Metals","Market leader; even APMEX has processing headaches","X-Large"),
    ("SD Bullion","sdbullion.com","Precious Metals","Price-competitive; thin margins = every bps = profit/loss","Large"),
    ("Gainesville Coins","gainesvillecoins.com","Precious Metals","Numismatic subjective value = chargeback-prone hybrid","Large"),
    ("Provident Metals","providentmetals.com","Precious Metals","High volume; price drops = systematic chargeback waves","Large"),
    ("Money Metals Exchange","moneymetals.com","Precious Metals","Conservative finance + bullion + subscription = three flags","Medium"),
    ("Scottsdale Bullion","scottsdalebullion.com","Precious Metals","High-ticket from wealthy clients = large $ per CB","Medium"),
    ("Texas Precious Metals","texasmetals.com","Precious Metals","Vault recurring fees + bullion sales = two processing needs","Medium"),
    ("Birch Gold Group","birchgold.com","Precious Metals","Heavy DR; IRA gold = financial product + commodity = dual flag","Large"),
    ("Goldco","goldco.com","Precious Metals","Fox News advertiser; large retirement transactions = big $","Large"),
    ("Noble Gold","noblegoldinvestments.com","Precious Metals","Radio DR + older demo + large purchases = CB risk","Medium"),
    ("Augusta Precious Metals","augustapreciousmetals.com","Precious Metals","Hall of Fame endorsements; large IRA = exposure","Large"),
    ("Silver.com","silver.com","Precious Metals","Marketplace; price swings = buyer remorse = CB waves","Medium"),
    ("Goldback","goldback.com","Precious Metals","So novel processors auto-decline without understanding","Small-Med"),
    ("MCM Modern Coin Mart","moderncoinmart.com","Precious Metals","Rare coin + bullion; subjective value = chargeback-prone","Medium"),
    ("PickDawgz","pickdawgz.com","Sports Picks","Subscription model; losers chargeback the service immediately","Small-Med"),
    ("Docs Sports Services","docsports.com","Sports Picks","Long-standing; repeat chargebacks from losing bettors","Small-Med"),
    ("WagerTalk","wagertalk.com","Sports Picks","Media + picks hybrid; subscription betting hard to place","Small-Med"),
    ("Pregame.com","pregame.com","Sports Picks","Picks marketplace = complex processor classification","Small-Med"),
    ("Sports Insights","sportsinsights.com","Sports Picks","Pro bettor data subscription = processor uncertain on class","Small-Med"),
    ("Action Network","actionnetwork.com","Sports Picks","Growing picks arm = processing complexity at scale","Medium"),
    ("BetQL","betql.com","Sports Picks","Subscription betting data = gray area by most processors","Small-Med"),
    ("RotoGrinders","rotogrinders.com","Sports Picks","DFS adjacent + subscription + picks = processor uncertainty","Small-Med"),
    ("Sharp Rank","sharprank.com","Sports Picks","AI picks = so novel processors have no category","Small"),
    ("Betstamp","betstamp.com","Sports Picks","Bet tracking + picks = gambling tool; classification varies","Small-Med"),
    ("Wesley Financial Group","wesleyfinancialgroup.com","High-Chargeback/Continuity","Timeshare exit = highest CB category; processors flee","Large"),
    ("Timeshare Exit Team","timeshareexitteam.com","High-Chargeback/Continuity","FTC targets this; processors flee = specialist opportunity","Medium"),
    ("FabFitFun","fabfitfun.com","High-Chargeback/Continuity","Value mismatch chargebacks every Q on box reveal","Large"),
    ("Loot Crate","lootcrate.com","High-Chargeback/Continuity","Post-bankruptcy; processor reluctance persists today","Medium"),
    ("Mystery Tackle Box","mysterytacklebox.com","High-Chargeback/Continuity","Niche subscription; gear mismatch = CBs on reveal","Small-Med"),
    ("Firstleaf Wine Club","firstleaf.com","High-Chargeback/Continuity","DTC wine + state laws + subscription = complex","Medium"),
    ("Winc Wine","winc.com","High-Chargeback/Continuity","DTC wine state-by-state compliance + subscription","Medium"),
    ("Cigar of Month Club","cigarsintl.com","High-Chargeback/Continuity","Tobacco + age-verified recurring billing = three flags","Small-Med"),
    ("Newton Group Transfers","newtongroupfinancials.com","High-Chargeback/Continuity","Timeshare transfer = even harder than exit to place","Small-Med"),
    ("Gentlemans Box","gentlemansbox.com","High-Chargeback/Continuity","Mens subscription; value mismatch = chargebacks","Small-Med"),
    ("Cigars International","cigarsintl.com","Tobacco/Cigars","Massive volume; tobacco compliance = its own beast","X-Large"),
    ("Famous Smoke Shop","famous-smoke.com","Tobacco/Cigars","Very large; tobacco + continuity = both flagged categories","Large"),
    ("JR Cigars","jrcigars.com","Tobacco/Cigars","Heritage brand; OG = probably hasn't shopped rates in years","Large"),
    ("Thompson Cigar","thompsoncigar.com","Tobacco/Cigars","Subscription cigar club; tobacco recurring billing at scale","Large"),
    ("Holts Cigars","holts.com","Tobacco/Cigars","High-end; affluent buyers; premium = high cost + expectations","Medium"),
    ("Cigarbid","cigarbid.com","Tobacco/Cigars","Auction model + tobacco = two unusual challenges","Medium"),
    ("Pipes and Cigars","pipesandcigars.com","Tobacco/Cigars","Broad tobacco; pipe tobacco = niche within niche","Medium"),
    ("Smokingpipes.com","smokingpipes.com","Tobacco/Cigars","Very high AOV on artisan pipes; collector expectations","Medium"),
    ("General Cigar DTC","generalcigar.com","Tobacco/Cigars","Manufacturer + DTC; massive volume; big opportunity","X-Large"),
    ("Perdomo Cigars","perdomocigars.com","Tobacco/Cigars","Family-owned growing DTC; needs processor that grows with them","Small-Med"),
    ("Snusdirect","snusdirect.com","Tobacco/Cigars","Import smokeless + cross-border + PACT = very hard","Small-Med"),
    ("Northerner","northerner.com","Tobacco/Cigars","Large intl smokeless; cross-border + tobacco = double flag","Medium"),
    ("Alec Bradley Cigars","alecbradley.com","Tobacco/Cigars","Premium boutique; growing DTC; premium = higher CB exposure","Small-Med"),
    ("Gotham Cigars","gothamcigars.com","Tobacco/Cigars","Local going national = processing transition = pitch now","Small-Med"),
    ("Rocky Mountain Cigar","rmcigars.com","Tobacco/Cigars","Event + tobacco merch; seasonal revenue + tobacco = unusual","Small"),
    ("Black Rifle Coffee","blackriflecoffee.com","Conservative/Political","Massive brand; faced processor issues from political positioning","Large"),
    ("Nine Line Apparel","ninelineapparel.com","Conservative/Political","Conservative brand; processors decline political brands","Medium"),
    ("Grunt Style","gruntstyle.com","Conservative/Political","Large veteran brand; military + political = processor scrutiny","Large"),
    ("Mammoth Nation","mammothnation.com","Conservative/Political","Political + continuity = two independent flags","Small-Med"),
    ("PublicSq","publicsq.com","Conservative/Political","Some processors decline on political brand principle alone","Medium"),
    ("Rumble","rumble.com","Conservative/Political","Political platform = high processor reluctance; large base","Large"),
    ("Epoch Times subscriptions","epochtimes.com","Conservative/Political","Very high sub volume; processors have explicitly declined them","Large"),
    ("Patriot Mobile","patriotmobile.com","Conservative/Political","Political carrier + telecom + cause donation = three flags","Small-Med"),
    ("Daily Wire Shop","dailywire.com","Conservative/Political","Large conservative brand; subscription + merch = friction","Large"),
    ("America First Policy","americafirstpolicy.com","Conservative/Political","Political org + merch + donations = complex processing","Small-Med"),
    ("Brightside Health","brightside.com","Mental Health/Controlled Rx","Controlled Rx + subscription = flagged by every processor","Medium"),
    ("Monument","joinmonument.com","Mental Health/Controlled Rx","Addiction medicine + controlled adjacent = high-risk cat","Small-Med"),
    ("Oar Health","oarhealth.com","Mental Health/Controlled Rx","AUD telehealth; naltrexone = controlled adjacent = flagged","Small-Med"),
    ("Ria Health","riahealth.com","Mental Health/Controlled Rx","AUD telehealth + controlled Rx = flagged everywhere","Small-Med"),
    ("Workit Health","workithealth.com","Mental Health/Controlled Rx","Addiction medicine DTC; controlled substance Rx = flagged","Medium"),
    ("Lear Capital","learcapital.com","Crypto/Alt Finance","Heavy DR; IRA gold = financial product + commodity = dual flag","Large"),
    ("Goldco IRA division","goldco.com","Crypto/Alt Finance","Fox News advertiser; large one-time retirement = big $","Large"),
    ("Ounce Gold Crypto","ounce.gold","Crypto/Alt Finance","So novel processors auto-decline; no category exists","Small"),
    ("Swan Bitcoin","swanbitcoin.com","Crypto/Alt Finance","Crypto + recurring billing = very flagged; growing fast","Medium"),
    ("Millennial Money DR","millennialmoney.com","Crypto/Alt Finance","DR affiliate model + gold/crypto = chargeback-prone","Small-Med"),
    ("BrightLife Direct TENS","brightlifedirect.com","Medical Devices/Gray Area","Class II adjacent pain relief claims = processor gray zone","Small-Med"),
    ("Infopathy","infopathy.com","Medical Devices/Gray Area","Digital homeopathy = major FDA risk = major processor risk","Small"),
    ("StemGenex","stemgenex.com","Medical Devices/Gray Area","Stem cell = FDA enforcement area = processor concern","Small-Med"),
    ("Cell Surgical Network","cellsurgical.com","Medical Devices/Gray Area","High-ticket stem cell; FDA uncertainty = processor uncertainty","Small-Med"),
    ("Ketamine Clinics LA","ketaminela.com","Medical Devices/Gray Area","Ketamine clinic online booking = controlled = flagged","Small-Med"),
    ("Solarc Systems","solarcfull.com","Medical Devices/Gray Area","UV therapy = medical device + psoriasis claims = flagged","Small-Med"),
    ("BEMER Group","bemergroup.com","Medical Devices/Gray Area","MLM + PEMF + circulation claims = triple flag","Small-Med"),
    ("Healthyline PEMF","healthyline.com","Medical Devices/Gray Area","PEMF + infrared combo; bold pain + healing claims; growing","Medium"),
    ("Vivos Therapeutics","vivos.com","Medical Devices/Gray Area","FDA-cleared but Class II = processor still may decline","Small-Med"),
    ("Therapeutic Laser Centers","verylasertech.com","Medical Devices/Gray Area","LLLT = FDA gray zone; health claims for pain/inflammation","Small-Med"),
]

conn = init_db()
c = conn.cursor()
inserted = 0
for m in MERCHANTS:
    try:
        c.execute("""
            INSERT OR IGNORE INTO merchants (name, website, category, pitch, vol_tier)
            VALUES (?, ?, ?, ?, ?)
        """, m)
        if c.rowcount: inserted += 1
    except Exception as e:
        print(f"  Skip {m[0]}: {e}")
conn.commit()
print(f"Seeded {inserted} merchants into ProcessorWatch database.")
